name: CI

on:
  pull_request:
    branches: ["dev", "test"]
    types: [opened, edited, closed]
permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repo
    - name: Checkout the repository
      uses: actions/checkout@v3

    # Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        cache: true
    
    # Build and examine Go source code
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Vet
      run: go vet -v ./...

  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m -v
 
  deploy:
    needs: [build, golangci]
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Build and push images to private repository
      - name: Build and push inventory-bmc-app
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: inventory-bmc-app
          tags: dev
          registry: ghcr.io
          githubOrg: ${{ github.repository_owner }}
          dockerfile: Dockerfile.inventory
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push discovery-bmc-app
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: discovery-bmc-app
          tags: dev
          registry: ghcr.io
          githubOrg: ${{ github.repository_owner }}
          dockerfile: Dockerfile.discovery
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push led-bmc-app
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: led-bmc-app
          tags: dev
          registry: ghcr.io
          githubOrg: ${{ github.repository_owner }}
          dockerfile: Dockerfile.led
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
